[project]
name = "classifier"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
  "pylangacq>=0.19.1",
  "beautifulsoup4>=4.14.3",
  "lxml>=6.0.2",
  "requests>=2.32.5",
  "pymysql>=1.1.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
